### ISSUE TITLE
Add package to (M)ELPA

### ISSUE THREAD

**Issue by sh-ow** [ccrusius/auth-source-xoauth2#4]
Title says it. As far as I could see, it currently isn't available via ELPA/MELPA.

**Comment by ccrusius** [comment]
Thanks for the suggestion - this has been on my list of things to do for a while, but I haven't had the time to do it yet.

**Comment by ccrusius** [comment]
FYI, this is now ongoing, Melpa pull request #6876.

**Comment by ccrusius** [comment]
It's in!
